"""Layout validation and artefact generation (design §6.1, §7.2). stdlib + PyYAML + jsonschema only."""

from __future__ import annotations

import json
import math
import pathlib

import yaml

HEADER = "# GENERATED by tools/layoutgen — do not edit.\n"
SCHEMA = pathlib.Path(__file__).resolve().parents[3] / "layouts" / "schema" / "layout.schema.json"

CHASSIS = (0.60, 0.50)
PAD = 0.05
PAYLOADS = {"unloaded": (0.0, 0.0), "small": (0.40, 0.40), "medium": (0.65, 0.65), "wide": (0.65, 1.00),
            "long": (1.20, 0.60)}
POOL = 12


class LayoutError(Exception):
    pass


def r3(v) -> float:
    return round(float(v), 3)


# ---- loading / validation ------------------------------------------------------------------------------------

def load_layout(path) -> dict:
    import jsonschema

    try:
        with open(path, encoding="utf-8") as f:
            layout = yaml.safe_load(f)
    except yaml.YAMLError as e:
        raise LayoutError(f"{path}: invalid YAML: {e}")
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    errs = sorted(jsonschema.Draft202012Validator(schema).iter_errors(layout), key=lambda e: list(map(str, e.path)))
    if errs:
        e = errs[0]
        loc = "/".join(str(p) for p in e.path) or "<root>"
        raise LayoutError(f"schema violation at '{loc}': {e.message}")
    validate_semantics(layout)
    return layout


def _in_poly(x, y, poly) -> bool:
    inside = False
    n = len(poly)
    for i in range(n):
        x1, y1 = poly[i]
        x2, y2 = poly[(i + 1) % n]
        if (y1 > y) != (y2 > y) and x < (x2 - x1) * (y - y1) / (y2 - y1) + x1:
            inside = not inside
    return inside


def _on_poly_edge(x, y, poly, eps=1e-9) -> bool:
    n = len(poly)
    for i in range(n):
        x1, y1 = poly[i]
        x2, y2 = poly[(i + 1) % n]
        cross = (x2 - x1) * (y - y1) - (y2 - y1) * (x - x1)
        if (abs(cross) <= eps and min(x1, x2) - eps <= x <= max(x1, x2) + eps
                and min(y1, y2) - eps <= y <= max(y1, y2) + eps):
            return True
    return False


def validate_semantics(layout: dict) -> None:
    names = {}
    for sect in ("stations", "intersections", "holds"):
        for i, v in enumerate(layout[sect]):
            if v["name"] in names:
                raise LayoutError(f"{sect}[{i}]: duplicate vertex name '{v['name']}'")
            names[v["name"]] = v
    rn = set()
    for r in layout["racks"]:
        if r["name"] in rn:
            raise LayoutError(f"racks: duplicate rack name '{r['name']}'")
        rn.add(r["name"])
    for i, ln in enumerate(layout["lanes"]):
        for k in ("from", "to"):
            if ln[k] not in names:
                raise LayoutError(f"lanes[{i}].{k}: unknown vertex '{ln[k]}'")
    for i, s in enumerate(layout["spawn"]):
        if s["vertex"] not in names:
            raise LayoutError(f"spawn[{i}].vertex: unknown vertex '{s['vertex']}'")
    directed = set()
    for ln in layout["lanes"]:
        directed.add((ln["from"], ln["to"]))
        if ln["bidirectional"]:
            directed.add((ln["to"], ln["from"]))
    for z in layout["zones"]:
        zn = z["name"]
        for k, v in enumerate(z["vertices"]):
            if v not in names:
                raise LayoutError(f"zone {zn}: vertices[{k}] unknown vertex '{v}'")
        for k, ln in enumerate(z["lanes"]):
            for end in ("from", "to"):
                if ln[end] not in names:
                    raise LayoutError(f"zone {zn}: lanes[{k}].{end} unknown vertex '{ln[end]}'")
            if (ln["from"], ln["to"]) not in directed:
                raise LayoutError(f"zone {zn}: lane {ln['from']}->{ln['to']} does not exist in lanes")
        for k, e in enumerate(z["entries"]):
            for end in ("entry", "hold"):
                if e[end] not in names:
                    raise LayoutError(f"zone {zn}: entries[{k}].{end} unknown vertex '{e[end]}'")
            if e["entry"] not in z["vertices"]:
                raise LayoutError(f"zone {zn}: entry '{e['entry']}' is not in the zone vertices")
            h = names[e["hold"]]["pose"]
            poly = z["polygon"]
            if _in_poly(h["x"], h["y"], poly) or _on_poly_edge(h["x"], h["y"], poly):
                raise LayoutError(f"zone {zn}: hold '{e['hold']}' lies inside the zone polygon")
        zverts = set(z["vertices"])
        hold_of = {e["entry"]: e["hold"] for e in z["entries"]}
        for a, b in sorted(directed):
            if b in zverts and a not in zverts and hold_of.get(b) != a:
                want = hold_of.get(b)
                raise LayoutError(
                    f"zone {zn}: lane {a}->{b} enters the zone at '{b}' but does not start at its hold "
                    f"({want if want else 'vertex is not a zone entry'}) (design §6.3 item 2)")


# ---- graph ---------------------------------------------------------------------------------------------------

def payload_geometry() -> dict:
    out = {}
    for name, (sx, sy) in PAYLOADS.items():
        px = max(CHASSIS[0], sx) + 2 * PAD
        py = max(CHASSIS[1], sy) + 2 * PAD
        out[name] = {"size_x": r3(sx), "size_y": r3(sy), "padded_x": r3(px), "padded_y": r3(py),
                     "rotation_diameter": r3(math.hypot(px, py))}
    return out


def build_graph(layout: dict):
    verts = {}
    for s in layout["stations"]:
        verts[s["name"]] = {"x": r3(s["pose"]["x"]), "y": r3(s["pose"]["y"]), "yaw": r3(s["pose"]["yaw"]),
                            "kind": s["type"]}
    for i in layout["intersections"]:
        verts[i["name"]] = {"x": r3(i["pose"]["x"]), "y": r3(i["pose"]["y"]), "kind": "intersection"}
    for h in layout["holds"]:
        verts[h["name"]] = {"x": r3(h["pose"]["x"]), "y": r3(h["pose"]["y"]), "kind": "hold"}
    zone_of = {}
    for z in layout["zones"]:
        for ln in z["lanes"]:
            zone_of[(ln["from"], ln["to"])] = z["name"]
        for e in z["entries"]:
            verts[e["entry"]].setdefault("zone_entry_of", []).append(z["name"])
            verts[e["hold"]].setdefault("hold_for", []).append(z["name"])
    geom = payload_geometry()
    edges = []
    for ln in layout["lanes"]:
        pairs = [(ln["from"], ln["to"])] + ([(ln["to"], ln["from"])] if ln["bidirectional"] else [])
        for a, b in pairs:
            va, vb = verts[a], verts[b]
            w = ln["clear_width_m"]
            e = {"from": a, "to": b, "length_m": r3(math.hypot(vb["x"] - va["x"], vb["y"] - va["y"])),
                 "clear_width_m": r3(w), "bidirectional": bool(ln["bidirectional"]),
                 "zone": zone_of.get((a, b)),
                 "feasible": {p: bool(w >= g["padded_y"] + 0.10 - 1e-9) for p, g in geom.items()},
                 "two_way_ok": {p: bool(w >= 2 * g["padded_y"] + 0.30 - 1e-9) for p, g in geom.items()}}
            if "speed_limit_mps" in ln:
                e["speed_limit_mps"] = ln["speed_limit_mps"]
            edges.append(e)
    edges.sort(key=lambda e: (e["from"], e["to"]))
    return verts, edges


def vertex_order(verts: dict) -> list:
    group = {"loading": 0, "delivery": 1, "park": 2, "intersection": 3, "hold": 4}
    return sorted(verts, key=lambda n: (group[verts[n]["kind"]], n))


def nav_graph(layout: dict, verts: dict, edges: list) -> dict:
    order = vertex_order(verts)
    idx = {n: i for i, n in enumerate(order)}
    vlist = []
    for n in order:
        v = verts[n]
        p = {"name": n}
        if v["kind"] == "park":
            p["is_parking_spot"] = True
            p["is_charger"] = True
        if v["kind"] == "hold":
            p["is_holding_point"] = True
        vlist.append([v["x"], v["y"], p])
    lanes = []
    for e in edges:
        p = {}
        if e.get("speed_limit_mps", 0) > 0:
            p["speed_limit"] = e["speed_limit_mps"]
        lanes.append([idx[e["from"]], idx[e["to"]], p])
    return {"building_name": layout["name"], "doors": {}, "lifts": {},
            "levels": {"L1": {"vertices": vlist, "lanes": lanes}}}


def zones_sidecar(layout: dict, verts: dict, edges: list) -> dict:
    zones = []
    for z in sorted(layout["zones"], key=lambda z: z["name"]):
        zones.append({"name": z["name"], "capacity": z["capacity"],
                      "edges": sorted([[ln["from"], ln["to"]] for ln in z["lanes"]]),
                      "vertices": sorted(z["vertices"]),
                      "entries": [{"entry": e["entry"], "hold": e["hold"]} for e in z["entries"]],
                      "polygon": [[r3(x), r3(y)] for x, y in z["polygon"]]})
    vout = {}
    for n in sorted(verts):
        v = dict(verts[n])
        for k in ("zone_entry_of", "hold_for"):
            if k in v:
                v[k] = sorted(v[k])
        vout[n] = v
    return {"schema_version": 1, "layout": layout["name"], "nav_graph": "nav_graph.yaml", "vertices": vout,
            "edges": edges, "zones": zones, "payloads": payload_geometry()}


# ---- map -----------------------------------------------------------------------------------------------------

def make_map(layout: dict):
    b = layout["bounds"]
    res = layout["resolution_m"]
    ox, oy = b["x_min"] - 0.5, b["y_min"] - 0.5
    w = round((b["x_max"] - b["x_min"] + 1.0) / res)
    h = round((b["y_max"] - b["y_min"] + 1.0) / res)
    racks = layout["racks"]
    rows = []
    for r in range(h - 1, -1, -1):          # PGM top row = max y
        y = oy + (r + 0.5) * res
        row = bytearray([254]) * w
        inside_y = b["y_min"] <= y <= b["y_max"]
        for c in range(w):
            x = ox + (c + 0.5) * res
            occ = not (inside_y and b["x_min"] <= x <= b["x_max"])
            if not occ:
                for k in racks:
                    if k["x_min"] <= x <= k["x_max"] and k["y_min"] <= y <= k["y_max"]:
                        occ = True
                        break
            if occ:
                row[c] = 0
        rows.append(bytes(row))
    pgm = b"P5\n# GENERATED by tools/layoutgen\n%d %d\n255\n" % (w, h) + b"".join(rows)
    meta = {"image": "map.pgm", "resolution": res, "origin": [r3(ox), r3(oy), 0.0], "negate": 0,
            "occupied_thresh": 0.65, "free_thresh": 0.25, "mode": "trinary"}
    return pgm, meta


# ---- world.sdf -----------------------------------------------------------------------------------------------

def _f(v) -> str:
    s = f"{round(float(v), 4):.4f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def _box_model(name, pose, size, color, static=True, collision=True, gravity=None):
    sz = " ".join(_f(v) for v in size)
    col = (f"        <collision name=\"collision\"><geometry><box><size>{sz}</size></box></geometry></collision>\n"
           if collision else "")
    grav = f"        <gravity>{'true' if gravity else 'false'}</gravity>\n" if gravity is not None else ""
    return (f"    <model name=\"{name}\">\n"
            f"      <static>{'true' if static else 'false'}</static>\n"
            f"      <pose>{' '.join(_f(v) for v in pose)}</pose>\n"
            f"      <link name=\"link\">\n{grav}{col}"
            f"        <visual name=\"visual\"><geometry><box><size>{sz}</size></box></geometry>"
            f"<material><ambient>{color}</ambient><diffuse>{color}</diffuse></material></visual>\n"
            f"      </link>\n    </model>\n")


STATION_COLOR = {"loading": "0.1 0.7 0.2 1", "delivery": "0.1 0.3 0.9 1", "park": "0.5 0.5 0.5 1"}


def make_world(layout: dict) -> str:
    b = layout["bounds"]
    wh = b.get("wall_height_m", 2.5)
    wt = b.get("wall_thickness_m", 0.2)
    xmin, xmax, ymin, ymax = b["x_min"], b["x_max"], b["y_min"], b["y_max"]
    lx = xmax - xmin + 2 * wt
    out = ['<?xml version="1.0" ?>\n',
           '<!-- GENERATED by tools/layoutgen - do not edit. -->\n',
           '<sdf version="1.9">\n', f'  <world name="{layout["name"]}">\n',
           '    <physics name="default_physics" type="ode">\n'
           '      <max_step_size>0.004</max_step_size>\n      <real_time_factor>1.0</real_time_factor>\n'
           '    </physics>\n',
           '    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>\n'
           '    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>\n'
           '    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>\n'
           '    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">\n'
           '      <render_engine>ogre2</render_engine>\n    </plugin>\n',
           '    <light type="directional" name="sun">\n      <cast_shadows>true</cast_shadows>\n'
           '      <pose>0 0 10 0 0 0</pose>\n      <diffuse>0.9 0.9 0.9 1</diffuse>\n'
           '      <specular>0.2 0.2 0.2 1</specular>\n      <direction>-0.5 0.1 -0.9</direction>\n    </light>\n',
           '    <model name="ground_plane">\n      <static>true</static>\n      <link name="link">\n'
           '        <collision name="collision"><geometry><plane><normal>0 0 1</normal><size>100 100</size></plane>'
           '</geometry></collision>\n'
           '        <visual name="visual"><geometry><plane><normal>0 0 1</normal><size>100 100</size></plane>'
           '</geometry><material><ambient>0.8 0.8 0.8 1</ambient><diffuse>0.8 0.8 0.8 1</diffuse></material>'
           '</visual>\n      </link>\n    </model>\n']
    cx, cy = (xmin + xmax) / 2, (ymin + ymax) / 2
    walls = [("wall_south", (cx, ymin - wt / 2, wh / 2), (lx, wt, wh)),
             ("wall_north", (cx, ymax + wt / 2, wh / 2), (lx, wt, wh)),
             ("wall_west", (xmin - wt / 2, cy, wh / 2), (wt, ymax - ymin, wh)),
             ("wall_east", (xmax + wt / 2, cy, wh / 2), (wt, ymax - ymin, wh))]
    for n, p, s in walls:
        out.append(_box_model(n, (*p, 0, 0, 0), s, "0.7 0.7 0.7 1"))
    for r in layout["racks"]:
        h = r.get("height_m", 2.0)
        out.append(_box_model(f"rack_{r['name']}", ((r["x_min"] + r["x_max"]) / 2, (r["y_min"] + r["y_max"]) / 2,
                                                     h / 2, 0, 0, 0),
                              (r["x_max"] - r["x_min"], r["y_max"] - r["y_min"], h), "0.6 0.4 0.2 1"))
    for s in layout["stations"]:
        out.append(_box_model(f"station_{s['name']}", (s["pose"]["x"], s["pose"]["y"], 0.005, 0, 0, 0),
                              (0.8, 0.8, 0.01), STATION_COLOR[s["type"]], collision=False))
    for i in range(POOL):
        out.append(_box_model(f"pkg_{i:02d}", (xmin - 3.0, ymin + 0.6 * i, 0.15, 0, 0, 0), (0.40, 0.40, 0.30),
                              "0.55 0.35 0.15 1", static=False, collision=False, gravity=False))
    out.append("  </world>\n</sdf>\n")
    return "".join(out)


# ---- sim2d ---------------------------------------------------------------------------------------------------

def make_sim2d(layout: dict, verts: dict, edges: list) -> dict:
    return {
        "name": layout["name"],
        "bounds": {k: layout["bounds"][k] for k in sorted(layout["bounds"])},
        "racks": [{"name": r["name"], "x_min": r["x_min"], "y_min": r["y_min"], "x_max": r["x_max"],
                   "y_max": r["y_max"], "height_m": r.get("height_m", 2.0)}
                  for r in sorted(layout["racks"], key=lambda r: r["name"])],
        "vertices": {n: {"x": verts[n]["x"], "y": verts[n]["y"], "kind": verts[n]["kind"]} for n in sorted(verts)},
        "edges": [{"from": e["from"], "to": e["to"], "length_m": e["length_m"], "zone": e["zone"]} for e in edges],
        "zones": [{"name": z["name"], "polygon": [[r3(x), r3(y)] for x, y in z["polygon"]],
                   "entries": [{"entry": e["entry"], "hold": e["hold"]} for e in z["entries"]]}
                  for z in sorted(layout["zones"], key=lambda z: z["name"])],
        "spawn": [{"robot_id": s["robot_id"], "vertex": s["vertex"], "yaw": float(s.get("yaw", 0.0))}
                  for s in layout["spawn"]],
    }


# ---- driver --------------------------------------------------------------------------------------------------

def _write_text(path: pathlib.Path, text: str) -> None:
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def _yaml_text(data) -> str:
    return HEADER + yaml.safe_dump(data, sort_keys=False, default_flow_style=None, width=120)


def generate_all(layout: dict, out) -> None:
    out = pathlib.Path(out)
    out.mkdir(parents=True, exist_ok=True)
    verts, edges = build_graph(layout)
    _write_text(out / "nav_graph.yaml", _yaml_text(nav_graph(layout, verts, edges)))
    _write_text(out / "zones.yaml", _yaml_text(zones_sidecar(layout, verts, edges)))
    pgm, meta = make_map(layout)
    (out / "map.pgm").write_bytes(pgm)
    _write_text(out / "map.yaml", _yaml_text(meta))
    _write_text(out / "world.sdf", make_world(layout))
    _write_text(out / "sim2d.json", json.dumps(make_sim2d(layout, verts, edges), indent=2, sort_keys=True) + "\n")
